version: '3'

volumes:
  pkg:
services:
  app:
    container_name: phinatest
    build: .
    command: npm run dev
    volumes:
      - .:/app
      - pkg:/app/node_modules
    ports:
      - "4444:4444"
